<?php

$copy = function() {
  $today = date("F j, Y, g:i a");
  $year = date("Y");

  $template = <<<HTML
/**
 * Generated By Figenator $today
 * PDO MySQL Generator
 *
 * link github
 * link author
 *
 * $year
 */

HTML;

  return $template;
};

function settingsTemplate($dataSettings = array()) {

  $default = array(
    "dbHost" => "localhost" ,
    "dbUser" => "root" ,
    "dbPassword" => "" ,
    "dbName" => "" ,
  );
  if(!empty($dataSettings)) {
    extract($dataSettings, EXTR_OVERWRITE);
  }
  extract($default, EXTR_SKIP);

  $ini     = <<<HTML
[SQL]
host     = $dbHost
user     = $dbUser
password = $dbPassword
dbname   = $dbName

HTML;

  return $ini;
}

function indexTemplate($dataIndex = array()) {
  global $copy;

  $default = array(
    "className" => 'defaultClass',
    "primaryKey" => 'id'
  );
  if(!empty($dataIndex)) {
    extract($dataIndex, EXTR_OVERWRITE);
  }
  extract($default, EXTR_SKIP);

  $template = <<<HTML
<?php
  require("$className.class.php");
  \$$className  = new $className();

/**
 * Your Create, Read, Update, Delete Here
 */

// Create
// \$className->yourProperty = 'Property Value';
// \$className->otherProperty = 'Property Value';
// \$creation = \$className->Create();

// Update
// \$className->yourProperty = 'Property Value';
// \$className->otherProperty = 'Property Value';
// \$saved = \$className->Save();

// Delete
// \$className->$primaryKey = 'Your Primary Key Value';
// \$delete= \$className->Delete();

// Get all $className
// \$$className = \$className->all();

HTML;

  return $template;
}

function classTemplate($dataClass = array()) {
  global $copy;

  $default = array(
    "easyCrudPath" => '../libs/easyCRUD.class.php' ,
    "className" => 'defaultClass',
    "tableName" => 'defaultTable',
    "primaryKey" => 'id',
  );

  if(!empty($dataClass)) {
    extract($dataClass, EXTR_OVERWRITE);
  }
  extract($default, EXTR_SKIP);

  $template = <<<HTML
<?php
  require_once("$easyCrudPath");

  class $className Extends Crud {

    # Your Table name
    protected \$table = '$tableName';

    # Primary Key of the Table
    protected \$pk	 = '$primaryKey';
  }

HTML;

  return $template;
}

function removeEmptyArray($var) {
  return !empty($var);
}
